### PR TITLE
feat: add snippets to disable each rule

### PR DESCRIPTION
**Pull request by EmilySeville7cfg**
The script is intended to modify `snippets/snippets.json` to automatically add auto generated snippets on each invocation.

Script intentionally made POSIX complaint.

### CODE REVIEW

**Comment by EmilySeville7cfg** [comment]
Will it be a nice idea to extend this script to be able:

- not just prepend generated snippets, but also to append
- filter out some generated snippets by their key

? I am asking as I think it would be cool to make the script a bit more general to run it outside of repo too to generate some user snippets.

**Comment by felipecrs** [comment]
This is really cool. It's not the [ideal way of enabling or disabling rules](https://github.com/vscode-shellcheck/vscode-shellcheck/issues/116), but definitely better than what we have already.

BTW prettier is failing. Maybe you can include `npx prettier --write snippets/snippets.json` as the last command in your script too?

**Comment by felipecrs** [comment]
Feel free to add your files to the cspell ignore list.

**Comment by felipecrs** [comment]
@EmilySeville7cfg, I made some changes related to formatting.

However, I ran your script again and it's making some changes to the `snippets.json` which I believe are wrong:

image

Related to escaping of `\` characters. Can you take a look?

**Comment by EmilySeville7cfg** [comment]
> Can you take a look?

I've tried to use Bash shebang, no such issue appeared. So I've switched script to Bash. Not sure what caused this behavior at this point.

**Review by felipecrs — APPROVED** [review]

**Comment by felipecrs** [comment]
Thanks for the PR @EmilySeville7cfg!

**Pull request merged**
