### PR TITLE
fix: honor folder-level and lang-specific settings

### PR DESCRIPTION
**Pull request by claui**
Until now, the ShellCheck extension has supported a single set of preferences per workspace and assumed that those preferences should always hold for the entire workspace.

However, [VS Code supports settings on more levels](https://code.visualstudio.com/docs/getstarted/settings#_settings-precedence), for example folder-level settings and [language-specific settings](https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings).

This PR adds missing support for both folder-level settings and language-specific settings.

## Folder-level settings

For an overview on workspace-folder-level settings, see VS Code’s [documentation on multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_settings).

For a practical example, see the [`workspace-folder.test.ts` suite](https://github.com/vscode-shellcheck/vscode-shellcheck/blob/c041bcc5e7552fa1f7b1156e166cc725786c5f86/test/suite/workspace-folder.test.ts).

## Language-specific settings

PR #696 introduced linting for shell-based DSLs. That feature requires support for language-specific settings to be functional.

Given that the fix also makes language-specific settings work, it also unblocks the [claui/vscode-packaging](https://github.com/claui/vscode-packaging) extension, making that extension ready for its first release.

## Error logging

The PR also adds basic error logging.

### CODE REVIEW

**Comment by claui** [comment]
> I'll wait for you to finish this PR before cutting the next release. Sounds good?

Makes sense 👍

**Comment by claui** [comment]
@felipecrs I’ve been dogfooding the PR for a couple of days and it seems to work flawlessly.

To be extra sure, I added a test suite today, which Works On My Machine™, but it’s failing on GitHub.

Any idea how to troubleshoot such a thing on CI?

**Comment by felipecrs** [comment]
Hm... I'm traveling these past days (and will be until August 28), with limited computer resources to be able to really help you.

I did not check the error message yet, but I would advise you to try putting some sleep statements where you may feel doubtful about it.

And retrying... Unfortunately we have noticed many intermittencies during test executions in CI.

**Comment by claui** [comment]
I can now reproduce the failures locally (thanks to the excellent [act](https://github.com/nektos/act) tool and a [minor tweak](https://github.com/vscode-shellcheck/vscode-shellcheck/compare/master...claui:vscode-shellcheck:local-ci-debug) to `ci.yaml`)!

The bad news: a six-hour debugging session has revealed that VS Code actually [doesn’t support entering a new workspace in tests](https://github.com/microsoft/vscode/blob/ac6a9ce604cfb6ebb5beb1aad7a9e0b42892232b/src/vs/workbench/services/workspaces/browser/abstractWorkspaceEditingService.ts#L363-L366). That’s too bad – hadn’t it been for the lack of support in VS Code, my test suite would have been fine!

I’ve completely run out of ideas how to make this testable. So I’m going to remove that test suite for now.

**Comment by claui** [comment]
Extracted the test suite to the `workspace-folder-test` branch in my fork:  
https://github.com/vscode-shellcheck/vscode-shellcheck/compare/master...claui:vscode-shellcheck:workspace-folder-test

**Comment by felipecrs** [comment]
Ok, we can try to make the tests work after. Are you done with the PR?

**Comment by claui** [comment]
> Ok, we can try to make the tests work after. Are you done with the PR?

Yep, ready to merge (unless you have any specific feedback)!

**Comment by claui** [comment]
Thanks @felipecrs and @timonwong!  
You helped unblock my [Packaging](https://marketplace.visualstudio.com/items?itemName=claui.packaging) extension, which is now live. :tada: :package:

**Comment by felipecrs** [comment]
Don't mention it, you did everything!

Thanks a lot for all your contributions, they are very much appreciated!

Success with your extension!

**Comment by claui** [comment]
Thanks @felipecrs, and you’re very welcome!

**Pull request merged**
