### PR TITLE
feat: prettify existing snippets and add new ones

### PR DESCRIPTION
**Pull request by EmilySeville7cfg**
I've prettified existing snippets to make them follow the same style as [these](https://github.com/github/vscode-github-actions/blob/a2f82688bd12a8a72c5197104ed759d637d2764d/snippets/snippets.json) ones.
Also I've added new snippets for optional checks and disabling all warnings at once. 😄

### CODE REVIEW

**Comment by felipecrs** [comment]
Prettier runs in CI to ensure a consistent style. Most likely this is why it is failing.

**Comment by felipecrs** [comment]
Prettier runs in CI to ensure a consistent style. Most likely this is why it is failing.

**Comment by EmilySeville7cfg** [comment]
I can't run Prettier as it fails when I open snippet file:

```
rror: Cannot find module 'prettier' from '/home/emilyseville7cfg/Documents/mine/bash/json-vscode-shellcheck'
	at e.exports [as sync] (/home/emilyseville7cfg/.vscode/extensions/esbenp.prettier-vscode-9.10.4/dist/extension.js:1:37268)
	at t.ModuleResolver.findPkg (/home/emilyseville7cfg/.vscode/extensions/esbenp.prettier-vscode-9.10.4/dist/extension.js:1:7353)
	at t.ModuleResolver.getPrettierInstance (/home/emilyseville7cfg/.vscode/extensions/esbenp.prettier-vscode-9.10.4/dist/extension.js:1:3313)
	at t.default.handleActiveTextEditorChanged (/home/emilyseville7cfg/.vscode/extensions/esbenp.prettier-vscode-9.10.4/dist/extension.js:1:9837)
	at handleActiveTextEditorChangedSync (/home/emilyseville7cfg/.vscode/extensions/esbenp.prettier-vscode-9.10.4/dist/extension.js:1:9439)
	at f.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at m.deliver (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
	at d.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:154048
	at f.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at m.deliver (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
	at d.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
	at m.acceptDocumentsAndEditorsDelta (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:13934)
	at m.$acceptDocumentsAndEditorsDelta (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:12249)
	at a.N (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:11223)
	at a.M (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:10941)
	at a.H (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:10034)
	at a.G (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:9015)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:7803
	at f.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at m.deliver (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
	at d.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
	at p.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14907)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:16556
	at f.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at m.deliver (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
	at d.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
	at p.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14907)
	at MessagePortMain.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:14682)
	at MessagePortMain.emit (node:events:526:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364)
```

**Comment by felipecrs** [comment]
You can run it from the terminal as well. Check the scripts in package.json, there is one which calls prettier --write or something.

**Comment by EmilySeville7cfg** [comment]
Why when I run `npm install` I get this:

```
npm ERR! Invalid comparator: ./see_vscode_vsce_issue_786

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/emilyseville7cfg/.npm/_logs/2023-03-26T16_47_21_373Z-debug-0.log
```

with this log:

```
0 verbose cli /home/emilyseville7cfg/.nvm/versions/node/v19.3.0/bin/node /home/emilyseville7cfg/.nvm/versions/node/v19.3.0/bin/npm
1 info using npm@9.2.0
2 info using node@v19.3.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/home/emilyseville7cfg/.nvm/versions/node/v19.3.0/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/emilyseville7cfg/Documents/mine/bash/json-vscode-shellcheck/.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/home/emilyseville7cfg/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/emilyseville7cfg/.nvm/versions/node/v19.3.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 6ms
17 timing npm:load:configload Completed in 6ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm install
21 verbose argv "install"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 2ms
24 timing npm:load:display Completed in 2ms
25 verbose logfile logs-max:10 dir:/home/emilyseville7cfg/.npm/_logs/2023-03-26T16_47_21_373Z-
26 verbose logfile /home/emilyseville7cfg/.npm/_logs/2023-03-26T16_47_21_373Z-debug-0.log
27 timing npm:load:logFile Completed in 3ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 13ms
31 silly logfile start cleaning logs, removing 1 files
32 timing config:load:flatten Completed in 0ms
33 timing arborist:ctor Completed in 1ms
34 silly logfile done cleaning log files
35 timing idealTree Completed in 80ms
36 timing command:install Completed in 84ms
37 verbose stack TypeError: Invalid comparator: ./see_vscode_vsce_issue_786
37 verbose stack     at Comparator.parse (/home/emilyseville7cfg/.nvm/versions/node/v19.3.0/lib/node_modules/npm/node_modules/semver/classes/comparator.js:38:13)
37 verbose stack     at new Comparator (/home/emilyseville7cfg/.nvm/versions/node/v19.3.0/lib/node_modules/npm/node_modules/semver/classes/comparator.js:22:10)
37 verbose stack     at /home/emilyseville7cfg/.nvm/versions/node/v19.3.0/lib/node_modules/npm/node_modules/semver/classes/range.js:133:47
37 verbose stack     at Array.map (<anonymous>)
37 verbose stack     at Range.parseRange (/home/emilyseville7cfg/.nvm/versions/node/v19.3.0/lib/node_modules/npm/node_modules/semver/classes/range.js:133:35)
37 verbose stack     at /home/emilyseville7cfg/.nvm/versions/node/v19.3.0/lib/node_modules/npm/node_modules/semver/classes/range.js:34:22
37 verbose stack     at Array.map (<anonymous>)
37 verbose stack     at new Range (/home/emilyseville7cfg/.nvm/versions/node/v19.3.0/lib/node_modules/npm/node_modules/semver/classes/range.js:34:8)
37 verbose stack     at Object.intersects (/home/emilyseville7cfg/.nvm/versions/node/v19.3.0/lib/node_modules/npm/node_modules/semver/ranges/intersects.js:3:8)
37 verbose stack     at OverrideSet.getEdgeRule (/home/emilyseville7cfg/.nvm/versions/node/v19.3.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/override-set.js:53:18)
38 verbose cwd /home/emilyseville7cfg/Documents/mine/bash/json-vscode-shellcheck
39 verbose Linux 5.15.0-67-generic
40 verbose node v19.3.0
41 verbose npm  v9.2.0
42 error Invalid comparator: ./see_vscode_vsce_issue_786
43 verbose exit 1
44 timing npm Completed in 110ms
45 verbose unfinished npm timer reify 1679849241399
46 verbose unfinished npm timer reify:loadTrees 1679849241400
47 verbose unfinished npm timer idealTree:init 1679849241401
48 verbose code 1
49 error A complete log of this run can be found in:
49 error     /home/emilyseville7cfg/.npm/_logs/2023-03-26T16_47_21_373Z-debug-0.log

```

**Comment by felipecrs** [comment]
I see that you are using Node 19. These are the versions we use:

https://github.com/vscode-shellcheck/vscode-shellcheck/blob/master/package.json#L293-L296

**Comment by EmilySeville7cfg** [comment]
It looks kinda strange, that CI fails even after reformatting. 🤔

**Comment by felipecrs** [comment]
Add "nullary" to cspell.json

**Comment by felipecrs** [comment]
You can always open the CI logs and see what's going on. :)

**Comment by EmilySeville7cfg** [comment]
They all passed! 🚀

**Comment by felipecrs** [comment]
Are you planning to add more after this PR? Just so I know whether to cut the next release now or not.

**Comment by EmilySeville7cfg** [comment]
> Are you planning to add more after this PR?

I guess everything I wanted already added. :)

**Comment by felipecrs** [comment]
Thanks for your contributions, @EmilySeville7cfg!

**Pull request merged**
