### PR TITLE
fix: cannot read properties of null on startup

### LINKED ISSUE #1039: 0.32.1 Throws repeated error on startup
TypeError: Cannot read properties of null (reading 'setResultCollections')
    at onDidCloseTextDocument (.../.vscode/extensions/timonwong.shellcheck-0.32.1-linux-x64/dist/extension.js:2:135241)

### PR DESCRIPTION
**Pull request by felipecrs**
I don't understand why this would be needed. @timonwong, do you have any clue by any chance?

@reporter123 you can help us out by testing if this PR fixes your issue or not.

Closes #1039

### CODE REVIEW

**Comment by felipecrs** [comment]
Here is the vsix for Linux AMD64:

[shellcheck-0.26.3.vsix.zip](https://github.com/vscode-shellcheck/vscode-shellcheck/files/11256498/shellcheck-0.26.3.vsix.zip)

After downloading, remove the .zip extension.

**Comment by reporter123** [comment]
Seems to have been fixed by https://github.com/vscode-shellcheck/vscode-shellcheck/commit/88221105b121ad5931cf7f2a1b7ddb2d7f9469e9 . Turns out this is hover triggered.

**Comment by felipecrs** [comment]
Alright, thank you!

**Comment by timonwong** [comment]
@felipecrs It's a method binding problem without `this` arg properly handled. Should be fixed in #1048

**Pull request closed without merging**
